---
sudo: false
language: ruby
cache: bundler
rvm:
  - 2.6.3
env:
  global:
    - CC_TEST_REPORTER_ID=1f7851d1df80cc24da6903abf795ee7a81a60b2cceb7eedd147c59c4ec232dd4

before_install: gem install bundler -v 2.0.2
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - bundle exec rspec
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
