name: Strait Test Suite

on:
  push:
  pull_request:
    # Branches from forks have the form 'user:branch-name' so we only run
    # this job on pull_request events for branches that look like fork
    # branches. Without this we would end up running this job twice for non
    # forked PRs, once for the push and then once for opening the PR.
    branches:
      - "**:**"

env:
  CC_TEST_REPORTER_ID: 1f7851d1df80cc24da6903abf795ee7a81a60b2cceb7eedd147c59c4ec232dd4

jobs:
  test:
    name: RSpec Test Suite
    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      fail-fast: false
      matrix:
        ruby:
          - ruby-2.6
          - ruby-2.7
          - ruby-3.0
          - ruby-3.1
          - truffleruby-20
        experimental: [false]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v1

      - name: Set up Ruby (${{ matrix.ruby }})
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true

      - name: Run Tests
        if: "! contains(toJSON(github.event.commits.*.message), '[skip ci]')"
        run: bundle exec rspec

      - name: Publish code coverage
        uses: paambaati/codeclimate-action@v3.0.0
